GET http://localhost:5000/api/activities/

###
GET http://localhost:5000/api/activities/sport

###
POST http://localhost:5000/api/activities
Content-Type: application/json

{
    "name": "Me",
    "price": 3,
    "category": "land"
}


###
DELETE http://localhost:5000/api/activities/61f95dd157232bbf94da7b3c


###
PATCH http://localhost:5000/api/activities/61f968f3a8c96e2ed9db5217
Content-Type: application/json

{
    "name" : "Banana",
    "price": 25
}